package com.devgun.shadcn_android.catalog

enum class CatalogDestination(
    val route: String,
    val title: String,
) {
    Button("button", "Button"),
    ButtonGroup("button_group", "Button Group"),
    Badge("badge", "Badge"),
    Separator("separator", "Separator"),
    Skeleton("skeleton", "Skeleton"),
    Spinner("spinner", "Spinner"),
    Label("label", "Label"),
    Typography("typography", "Typography"),
    AspectRatio("aspect_ratio", "Aspect Ratio"),
    Avatar("avatar", "Avatar"),
    Input("input", "Input"),
    Textarea("textarea", "Textarea"),
    InputGroup("input_group", "Input Group"),
    InputOtp("input_otp", "Input OTP"),
    Checkbox("checkbox", "Checkbox"),
    Switch("switch", "Switch"),
    RadioGroup("radio_group", "Radio Group"),
    Slider("slider", "Slider"),
    Progress("progress", "Progress"),
    Select("select", "Select"),
    Field("field", "Field"),
    Toggle("toggle", "Toggle"),
    ToggleGroup("toggle_group", "Toggle Group"),
    Card("card", "Card"),
    Alert("alert", "Alert"),
    Empty("empty", "Empty"),
    Item("item", "Item"),
    Collapsible("collapsible", "Collapsible"),
    Accordion("accordion", "Accordion"),
    Dialog("dialog", "Dialog"),
    AlertDialog("alert_dialog", "Alert Dialog"),
    Sheet("sheet", "Sheet"),
    Drawer("drawer", "Drawer"),
    DropdownMenu("dropdown_menu", "Dropdown Menu"),
    ContextMenu("context_menu", "Context Menu"),
    Snackbar("snackbar", "Snackbar"),
    Tabs("tabs", "Tabs"),
    Breadcrumb("breadcrumb", "Breadcrumb"),
    Pagination("pagination", "Pagination"),
    BottomNavigation("bottom_navigation", "Bottom Navigation"),
    NavigationRail("navigation_rail", "Navigation Rail"),
    Sidebar("sidebar", "Sidebar"),
    Calendar("calendar", "Calendar"),
    DatePicker("date_picker", "Date Picker"),
    Combobox("combobox", "Combobox"),
    Table("table", "Table"),
    DataTable("data_table", "Data Table"),
    Carousel("carousel", "Carousel"),
    ScrollArea("scroll_area", "Scroll Area"),
    Chart("chart", "Chart"),
    Message("message", "Message"),
    Attachment("attachment", "Attachment"),
    Questionnaire("questionnaire", "Questionnaire"),
    ;

    companion object {
        val entriesSorted = entries.sortedBy { it.title }
    }
}
