package com.devgun.shadcn_android.ui.theme

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

@Immutable
data class ShadcnColors(
    val background: Color,
    val foreground: Color,
    val card: Color,
    val cardForeground: Color,
    val popover: Color,
    val popoverForeground: Color,
    val primary: Color,
    val primaryForeground: Color,
    val secondary: Color,
    val secondaryForeground: Color,
    val muted: Color,
    val mutedForeground: Color,
    val accent: Color,
    val accentForeground: Color,
    val destructive: Color,
    val destructiveForeground: Color,
    val border: Color,
    val input: Color,
    val ring: Color,
    val chart1: Color,
    val chart2: Color,
    val chart3: Color,
    val chart4: Color,
    val chart5: Color,
    val sidebar: Color,
    val sidebarForeground: Color,
    val sidebarPrimary: Color,
    val sidebarPrimaryForeground: Color,
    val sidebarAccent: Color,
    val sidebarAccentForeground: Color,
    val sidebarBorder: Color,
    val sidebarRing: Color,
)

val LocalShadcnColors = staticCompositionLocalOf { lightShadcnColors }

val lightShadcnColors = ShadcnColors(
    background = Color(0xFFFFFFFF),
    foreground = Color(0xFF0A0A0A),
    card = Color(0xFFFFFFFF),
    cardForeground = Color(0xFF0A0A0A),
    popover = Color(0xFFFFFFFF),
    popoverForeground = Color(0xFF0A0A0A),
    primary = Color(0xFF171717),
    primaryForeground = Color(0xFFFAFAFA),
    secondary = Color(0xFFF5F5F5),
    secondaryForeground = Color(0xFF171717),
    muted = Color(0xFFF5F5F5),
    mutedForeground = Color(0xFF737373),
    accent = Color(0xFFF5F5F5),
    accentForeground = Color(0xFF171717),
    destructive = Color(0xFFE7000B),
    destructiveForeground = Color(0xFFFAFAFA),
    border = Color(0xFFE5E5E5),
    input = Color(0xFFE5E5E5),
    ring = Color(0xFFA3A3A3),
    chart1 = Color(0xFFF54900),
    chart2 = Color(0xFF009689),
    chart3 = Color(0xFF104E64),
    chart4 = Color(0xFFFFB900),
    chart5 = Color(0xFFFE9A00),
    sidebar = Color(0xFFFAFAFA),
    sidebarForeground = Color(0xFF0A0A0A),
    sidebarPrimary = Color(0xFF171717),
    sidebarPrimaryForeground = Color(0xFFFAFAFA),
    sidebarAccent = Color(0xFFF5F5F5),
    sidebarAccentForeground = Color(0xFF171717),
    sidebarBorder = Color(0xFFE5E5E5),
    sidebarRing = Color(0xFFA3A3A3),
)

val darkShadcnColors = ShadcnColors(
    background = Color(0xFF0A0A0A),
    foreground = Color(0xFFFAFAFA),
    card = Color(0xFF171717),
    cardForeground = Color(0xFFFAFAFA),
    popover = Color(0xFF171717),
    popoverForeground = Color(0xFFFAFAFA),
    primary = Color(0xFFE5E5E5),
    primaryForeground = Color(0xFF171717),
    secondary = Color(0xFF262626),
    secondaryForeground = Color(0xFFFAFAFA),
    muted = Color(0xFF262626),
    mutedForeground = Color(0xFFA3A3A3),
    accent = Color(0xFF262626),
    accentForeground = Color(0xFFFAFAFA),
    destructive = Color(0xFFFF6467),
    destructiveForeground = Color(0xFFFAFAFA),
    border = Color(0x1AFFFFFF),
    input = Color(0x26FFFFFF),
    ring = Color(0xFF737373),
    chart1 = Color(0xFF1447E6),
    chart2 = Color(0xFF00BC7D),
    chart3 = Color(0xFFFE9A00),
    chart4 = Color(0xFFAD46FF),
    chart5 = Color(0xFFFF2056),
    sidebar = Color(0xFF171717),
    sidebarForeground = Color(0xFFFAFAFA),
    sidebarPrimary = Color(0xFF1447E6),
    sidebarPrimaryForeground = Color(0xFFFAFAFA),
    sidebarAccent = Color(0xFF262626),
    sidebarAccentForeground = Color(0xFFFAFAFA),
    sidebarBorder = Color(0x1AFFFFFF),
    sidebarRing = Color(0xFF737373),
)
